### ISSUE TITLE
Task 1.3 (Make the map functional)

### ISSUE THREAD

**Issue by ggams2020** [cs169/fa23-chips-10.5-34#5]
-  Figure out which URL you’ll need to modify so that a click on a county triggers the `search#search` route --> make the map functional
- Ensure you are also writing proper tests in Cucumber for map actions

**Comment by ggams2020** [comment]
@RVaidya149124092u35 pls put up a PR and link it to this issue!

**Comment by RVaidya149124092u35** [comment]
https://github.com/cs169/fa23-chips-10.5-34/pull/14
